spring.application.name=lajoju
server.port=${SERVER_PORT:8083}
security.jwt.public-key-location=${SECURITY_JWT_PUBLIC_KEY_LOCATION:file:../secrets/jwt-public.pem}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/lajoju?currentSchema=agendamento}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.flyway.default-schema=${DB_SCHEMA:agendamento}
spring.flyway.schemas=${DB_SCHEMA:agendamento}
services.usuario.base-url=${USUARIO_SERVICE_URL:http://localhost:8081}
services.produto.base-url=${PRODUTO_SERVICE_URL:http://localhost:8082}
