spring.application.name=lajoju
server.port=${SERVER_PORT:8082}
security.jwt.public-key-location=${SECURITY_JWT_PUBLIC_KEY_LOCATION:file:../secrets/jwt-public.pem}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/lajoju?currentSchema=produto}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.flyway.default-schema=${DB_SCHEMA:produto}
spring.flyway.schemas=${DB_SCHEMA:produto}
